version: '3.7'

networks:
  gitlab-network: {}
services:
  gitlab-web:
    
    build: 
      context: ./gitlab
    container_name: gitlab-web
    
    volumes:
      - './gitlab-config:/etc/gitlab'
      - './gitlab-logs:/var/log/gitlab'
      - './gitlab-data:/var/opt/gitlab'
    ports:
      - '30022:22'
      - '8086:80'
      - '4433:443'
      - '4567:4567'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['gitlab_shell_ssh_port'] = 30022
        registry_external_url 'http://gitlab-web:4567'
       
    networks:
      - gitlab-network
  jenkins-web:
    build: 
      context: ./jenkins
       
    container_name: jenkins-web
    
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      
    ports:
      - 8080:8080
      - 50000:50000

    restart: on-failure
    
    
      
    networks:
      - gitlab-network


volumes:
    jenkins_home:
